// Generated by dev/tools/build_ladder_map.py.
textures/peace_ladder/floor
{
    {
        map $whiteimage
        rgbGen const ( 0.25 0.29 0.34 )
    }
}
textures/peace_ladder/wall
{
    {
        map $whiteimage
        rgbGen const ( 0.12 0.19 0.26 )
    }
}
textures/peace_ladder/platform
{
    {
        map $whiteimage
        rgbGen const ( 0.33 0.38 0.42 )
    }
}
textures/peace_ladder/ladder
{
    surfaceparm ladder
    {
        map $whiteimage
        rgbGen const ( 0.13 0.14 0.16 )
    }
}
textures/peace_ladder/rail
{
    {
        map $whiteimage
        rgbGen const ( 0.97 0.61 0.12 )
    }
}
textures/peace_ladder/rung
{
    {
        map $whiteimage
        rgbGen const ( 0.76 0.84 0.88 )
    }
}
