#!/usr/bin/env python3
"""mapgen.py - programmatic Quake 3 (.map) geometry generator.

Emits the classic idTech3 brush format that q3map2 consumes. Box brushes are
generated with their six plane windings verified at generation time via a
cross-product check, so the geometry is guaranteed to face outward correctly
(a brush with an inverted plane silently fails to compile in Radiant tools).

Run with no arguments to (re)generate the bundled maps into ../src.

    python3 mapgen.py [output_dir]
"""

import os
import sys


# ---------------------------------------------------------------------------
# tiny vector helpers (plain tuples, no numpy dependency)
# ---------------------------------------------------------------------------
def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def fmt(p):
    # q3map2 is happy with integers/short decimals; keep it readable.
    return "%g %g %g" % (p[0], p[1], p[2])


# Six axis-aligned faces as (axis, sign) -> outward normal direction.
_FACES = [(0, +1), (0, -1), (1, +1), (1, -1), (2, +1), (2, -1)]


def _face_points(mins, maxs, axis, sign):
    """Return the four corners of one axis-aligned face (any 3 define it)."""
    const = maxs[axis] if sign > 0 else mins[axis]
    a, b = [i for i in range(3) if i != axis]
    corners = []
    for va, vb in ((mins[a], mins[b]), (maxs[a], mins[b]),
                   (maxs[a], maxs[b]), (mins[a], maxs[b])):
        p = [0, 0, 0]
        p[axis] = const
        p[a] = va
        p[b] = vb
        corners.append(tuple(p))
    return corners


def box(mins, maxs, shader, scale=0.5):
    """Emit a single axis-aligned box brush as map text.

    The plane winding for each face is corrected so its normal points out of
    the solid, regardless of how the corners happen to be ordered.
    """
    lines = ["\t// brush", "\t{"]
    for axis, sign in _FACES:
        normal = [0, 0, 0]
        normal[axis] = sign
        p0, p1, p2, _ = _face_points(mins, maxs, axis, sign)
        # q3map2 computes the plane normal as (p0 - p1) x (p2 - p1).
        computed = cross(sub(p0, p1), sub(p2, p1))
        if dot(computed, normal) < 0:
            p0, p2 = p2, p0  # flip winding so the normal faces outward
        lines.append(
            "\t\t( %s ) ( %s ) ( %s ) %s 0 0 0 %g %g 0 0 0"
            % (fmt(p0), fmt(p1), fmt(p2), shader, scale, scale))
    lines.append("\t}")
    return "\n".join(lines)


class Q3Map:
    """Accumulates worldspawn brushes plus point/brush entities."""

    def __init__(self, **worldkeys):
        self.world_keys = {"classname": "worldspawn"}
        self.world_keys.update(worldkeys)
        self.world_brushes = []
        self.entities = []

    def box(self, mins, maxs, shader, scale=0.5):
        self.world_brushes.append(box(mins, maxs, shader, scale))

    def entity(self, classname, origin=None, **keys):
        e = {"classname": classname}
        if origin is not None:
            e["origin"] = "%g %g %g" % tuple(origin)
        for k, v in keys.items():
            e[k] = str(v)
        self.entities.append(e)

    def render(self):
        out = ["// Generated by mapgen.py - do not hand-edit; edit the script.",
               "// entity 0", "{"]
        for k, v in self.world_keys.items():
            out.append('"%s" "%s"' % (k, v))
        out.extend(self.world_brushes)
        out.append("}")
        for i, e in enumerate(self.entities, 1):
            out.append("// entity %d" % i)
            out.append("{")
            for k, v in e.items():
                out.append('"%s" "%s"' % (k, v))
            out.append("}")
        return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Map: dm_outpost - a small modern-military free-for-all arena.
# Interior is a sealed 1024x1024 room, 448 tall, with a raised central
# command platform (rocket launcher) reached by stairs on two sides, plus
# crate cover and perimeter weapon/health placement.
# ---------------------------------------------------------------------------

# Shader names target stock baseq3 (pak0.pk3). They are easy to swap for the
# mod's own texture set - see mapping/README.md.
FLOOR = "base_floor/metalfloor_wall_5"
WALL = "base_wall/metaltech07"
CEIL = "base_ceiling/ceiling1_3"
CRATE = "base_wall/metaltechborder"
PLATE = "base_floor/clangfloor_b"
CAULK = "common/caulk"


def build_outpost():
    m = Q3Map(message="Outpost",
              _ambient="16",     # base fill light so nothing is pure black
              _minlight="24",
              music="music/sonic5.wav")

    R = 512        # interior half-extent (X and Y span -512..512)
    H = 448        # interior height
    T = 32         # wall / slab thickness

    # --- shell -------------------------------------------------------------
    m.box((-R - T, -R - T, -T), (R + T, R + T, 0), FLOOR)          # floor slab
    m.box((-R - T, -R - T, H), (R + T, R + T, H + T), CEIL)        # ceiling slab
    m.box((-R - T, -R - T, 0), (-R, R + T, H), WALL)               # west wall
    m.box((R, -R - T, 0), (R + T, R + T, H), WALL)                 # east wall
    m.box((-R, -R - T, 0), (R, -R, H), WALL)                       # south wall
    m.box((-R, R, 0), (R, R + T, H), WALL)                         # north wall

    # --- central command platform -----------------------------------------
    P = 192        # platform half-extent
    PH = 96        # platform top height
    m.box((-P, -P, 0), (P, P, PH), CRATE)
    m.box((-P + 8, -P + 8, PH), (P - 8, P - 8, PH + 2), PLATE)     # top trim cap

    # stairs up the south and north faces (6 steps of 16, 24 deep, 192 wide)
    for i in range(6):
        height = 16 * (i + 1)
        depth = 24
        # south stairs ascend going north toward the platform
        ys = -P - depth * (6 - i)
        m.box((-96, ys, 0), (96, ys + depth, height), CRATE)
        # north stairs ascend going south toward the platform
        yn = P + depth * (5 - i)
        m.box((-96, yn, 0), (96, yn + depth, height), CRATE)

    # --- crate cover scattered around the floor ----------------------------
    crates = [
        ((-400, -96, 0), (-336, 96, 48)),   # west
        ((336, -96, 0), (400, 96, 48)),     # east
        ((-96, -400, 0), (96, -336, 56)),   # south
        ((-96, 336, 0), (96, 400, 56)),     # north
        ((-420, -420, 0), (-356, -356, 40)),  # SW corner step-up
        ((356, 356, 0), (420, 420, 40)),      # NE corner step-up
    ]
    for mn, mx in crates:
        m.box(mn, mx, CRATE)

    # --- spawns (6, ringing the arena, facing the centre) ------------------
    spawns = [
        ((-420, -420, 24), 45), ((420, -420, 24), 135),
        ((-420, 420, 24), 315), ((420, 420, 24), 225),
        ((0, -440, 24), 90), ((0, 440, 24), 270),
    ]
    for origin, ang in spawns:
        m.entity("info_player_deathmatch", origin, angle=ang)
    # intermission camera looking down over the platform
    m.entity("info_player_intermission", (0, -300, 360), angle=70)

    # --- weapons + ammo ----------------------------------------------------
    m.entity("weapon_rocketlauncher", (0, 0, PH + 24))            # platform prize
    m.entity("ammo_rockets", (0, -P - 12, PH + 16))
    m.entity("weapon_railgun", (-440, 0, 40))
    m.entity("ammo_slugs", (-440, 80, 40))
    m.entity("weapon_shotgun", (0, -380, 80))
    m.entity("ammo_shells", (80, -380, 80))
    m.entity("weapon_machinegun", (0, 380, 80))
    m.entity("ammo_bullets", (-80, 380, 80))
    m.entity("weapon_grenadelauncher", (440, 0, 40))
    m.entity("ammo_grenades", (440, -80, 40))

    # --- health + armor ----------------------------------------------------
    m.entity("item_armor_combat", (-420, 420, 64))   # NW corner crate
    m.entity("item_health_large", (420, -420, 24))   # SE corner
    for x, y in ((-380, 0), (380, 0), (0, -380), (0, 380)):
        m.entity("item_health", (x, y, 24))
    for x, y in ((-200, -200), (200, 200), (-200, 200), (200, -200)):
        m.entity("item_armor_shard", (x, y, 24))

    # --- lighting ----------------------------------------------------------
    for x in (-320, 0, 320):
        for y in (-320, 0, 320):
            m.entity("light", (x, y, H - 48), light=300)
    m.entity("light", (0, 0, PH + 160), light=260, _color="0.9 0.95 1.0")

    return m


MAPS = {"dm_outpost": build_outpost}


def main(argv):
    out_dir = argv[1] if len(argv) > 1 else \
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")
    out_dir = os.path.abspath(out_dir)
    os.makedirs(out_dir, exist_ok=True)
    for name, builder in MAPS.items():
        path = os.path.join(out_dir, name + ".map")
        with open(path, "w") as f:
            f.write(builder().render())
        print("wrote %s" % path)


if __name__ == "__main__":
    main(sys.argv)
